### PR TITLE
add private github package support using personal access token

### PR DESCRIPTION
**Pull request by rYuuk**
#### Changes
- Added changes from https://github.com/game-ci/unity-builder/pull/278

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [X] Readme (updated or not needed)
- [ ] Tests (added, updated or not needed)

@webbertakken I tried getting all the changes from the above mentioned PR. I am not really sure if its complete.
I am not good with js, so I wasn't able to fix the test failing and linting issues. It would be great if I could get some help.

### CODE REVIEW

**Review by davidmfinol — APPROVED** [review]

**Comment by shubear** [comment]
In relation to https://github.com/game-ci/unity-test-runner/issues/136, this change may have broken any existing repo's using ssh. Our manifest uses `ssh://git@github.com` and this is the output I am seeing

```
Activation complete.
/github/workspace
/steps/set_gitcredential.sh: line 1: ﻿#!/usr/bin/env: No such file or directory
GIT_PRIVATE_TOKEN is set configuring git credentials
---------- git config --list -------------
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
```

This is what my action config looks like
```
- uses: game-ci/unity-test-runner@v2
   with:
          sshAgent: ${{ env.SSH_AUTH_SOCK }}
```

**Comment by shubear** [comment]
I noted this in the logs
```
 --env GIT_PRIVATE_TOKEN=undefined 
 ```
Even though this is what my action looks like
```
      - uses: game-ci/unity-test-runner@v2
        with:
          sshAgent: ${{ env.SSH_AUTH_SOCK }}
          gitPrivateToken: ''
```

**Comment by shubear** [comment]
working around this issue by using `- uses: game-ci/unity-test-runner@v2.0-alpha-6`, incase anyone is facing this

**Comment by davidmfinol** [comment]
> working around this issue by using `- uses: game-ci/unity-test-runner@v2.0-alpha-6`, incase anyone is facing this

@shubear Can you try `- uses: game-ci/unity-test-runner@main` and see if that works for you? I believe the regression may be fixed by a change I recently made that hasn't been rolled into v2 yet.

**Comment by davidmfinol** [comment]
Hm... with v2, I get logs that match the initial error scenario:
```
Activation complete.
/github/workspace
/steps/set_gitcredential.sh: line 1: ﻿#!/usr/bin/env: No such file or directory
GIT_PRIVATE_TOKEN is set configuring git credentials
```
But with main, I get this:
```
Activation complete.
/github/workspace
/steps/set_gitcredential.sh: line 1: ﻿#!/usr/bin/env: No such file or directory
GIT_PRIVATE_TOKEN unset skipping
```
You still get the `GIT_PRIVATE_TOKEN is set configuring git credentials` message even with `game-ci/unity-test-runner@main`?

**Comment by davidmfinol** [comment]
I think we can safely ignore the `/steps/set_gitcredential.sh: line 1: ﻿#!/usr/bin/env: No such file or directory` message.
The issue I'm worried about is being unable to access git private repos with sshAgent.
If you're seeing a problem with sshAgent, can you update on https://github.com/game-ci/unity-test-runner/issues/157 ?

**Pull request merged**
