### PR TITLE
allow space in between words of project name

### PR DESCRIPTION
**Pull request by webbertakken**
#### Changes

- Allows a space in the project path

Not sure if it's a great idea to allow this, but let's at least test if it works at all.

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated or not needed)
- [x] Tests (added, updated or not needed)

### CODE REVIEW

**Review by davidmfinol — DISMISSED** [review]

**Comment by webbertakken** [comment]
I do not think we should be merging this, as the person who wanted to try it didn't get it to work and this change opens us up for many more potential issues.

**Comment by achimmihca** [comment]
> as the person who wanted to try it didn't get it to work

It is working perfectly fine for us.

I have an unerelated issue with unity 2021.2.0f1 and macOS build when using unity-builder. 

But unity-test-runner works good for us.
Ahh, there was only a minor issue that ls command to print project directory is not quoted. The unity build works however

**Comment by webbertakken** [comment]
Ah I see. Approving from my side, but let's see what @davidmfinol thinks about merging this as well.

**Review by davidmfinol — APPROVED** [review]

**Comment by davidmfinol** [comment]
If its been successfully tested in this branch, then I think its fine to merge.

**Comment by davidmfinol** [comment]
@webbertakken I went ahead and rebuilt `action/index.js`, if you want to merge.

**Comment by webbertakken** [comment]
Thanks!

**Pull request merged**
