### PR TITLE
Feature/add support for licensing server

### PR DESCRIPTION
**Pull request by simensan**
#### Changes

- Added support for unity licensing server like for unity builder. 

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [ x] Readme (updated or not needed)
- [ x] No tests added

### CODE REVIEW

**Review by webbertakken — APPROVED** [review]

**Comment by webbertakken** [comment]
Sorry, this PR slipped my attention. Could you please merge main into your branch or rebase, and then run `yarn build` to regenerate the dist files please? Then we're ready to merge this.

**Comment by simensan** [comment]
I will look more at this tomorrow, I tried quickly, but I am getting this during the push hook after the merge:
unity-test-runner\src\index.ts
   1:1   error  Use default import for module `path`  unicorn/import-style
  16:21  error  '_' is defined but never used         no-unused-vars

I am not sure why I am only getting it on windows platform? I do not get the errors running yarn lint via wsl. And it seems like the yarn lint was also successful on the github actions run on previous PR merged in.

**Comment by webbertakken** [comment]
So sorry about that. Fixed in https://github.com/game-ci/unity-test-runner/pull/199

**Comment by simensan** [comment]
No worries, could probably have fixed it myself, but not a ts/js dev myself, so would have just taken a lot longer :) 
I have pushed the merge now.  

Thanks!

**Comment by webbertakken** [comment]
Thanks for taking care of that. It's in now :)

**Pull request merged**
