### PR TITLE
Mount known_hosts from home directory for using ssh-agent on self-hosted runner

### PR DESCRIPTION
**Pull request by chromee**
When using self-hosted runner, name of the user running runner is not necessarily the runner.
So known_hosts need to be mounted from .ssh folder in home directory of user running self-hosted runner.

helped by @nikaera

#### Changes

- mount .ssh/known_hosts from the running user's home directory

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated or not needed)
- [x] Tests (added, updated or not needed)

### CODE REVIEW

**Comment by webbertakken** [comment]
Does the project get checked out in that home dir as well?

Should we be updating all occurrences of that directory?

**Comment by chromee** [comment]
When installing the self hosted runner, specify a working directory for the runner.
The project will be checked out to that working directory.

Yes, we should update where assuming GitHub runners.

**Comment by webbertakken** [comment]
I lost context. What is the status of this PR?

**Comment by chromee** [comment]
Sorry for the late reply.
I found further improvements and will re-submit a PR.
So I close this PR.

**Pull request closed without merging**
