### PR TITLE
Add support for Scoped Registries

### PR DESCRIPTION
**Pull request by nvandessel**
#### Changes

- Adds new arguments to the action named `scopedRegistryUrl` and `registryScopes`.
- Expects to receive a `UPM_REGISTRY_TOKEN` as an environment variable.
- These values are used when `packageMode` is `true` and we test a Unity package.
- During testing the following happens.
    - If a `scopedRegistryUrl` is provided, validation occurs to ensure `registryScopes` are supplied as well
    - The test project is built to test our package, and opened to generate a `manifest.json` (existing functionality)
    - While adding the package under test to the `manifest.json` we also add the scoped registry and its scopes
    - If a `UPM_REGISTRY_TOKEN` is found, then a `.upmconfig.toml` is created at the `$HOME` directory
- Further information on scoped registries can be found in the [Unity docs](https://docs.unity3d.com/Manual/upm-scoped.html).

#### Related Issues

- Closes https://github.com/game-ci/unity-test-runner/issues/225

#### Related PRs

- Documentation PR https://github.com/game-ci/documentation/pull/453

#### Successful Workflow Run Link

PRs don't have access to secrets so you will need to provide a link to a successful run
of the workflows from your own repo.

- [Successful run on public registry](https://github.com/luminopia/unity-test-runner/actions/runs/8088760608)
- [Successful run on private registry](https://github.com/luminopia/unity-test-runner/actions/runs/8088606038)
    - Note, I've removed the logs from the above run to avoid exposing any information about the private registry (mainly the URL), simply out of an abundance of caution. While I am passing the URL through GH secrets, Unity will still output the URL when showing which registry packages were resolved from.

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [x] Docs (If new inputs or outputs have been added or changes to behavior that should be documented. Please make a PR
      in the [documentation repo](https://github.com/game-ci/documentation))
- [x] Readme (updated or not needed)
- [x] Tests (added, updated or not needed)
    - I did not add any tests, but I did add the additional `com.dependencyexample.testpackage` to the same directory as the existing package. By default it is setup to have a dependency from a popular OpenUPM package [UniTask](https://openupm.com/packages/com.cysharp.unitask/), and is tested via the added job `testPackageRunnerWithScopeRegistry`.

### CODE REVIEW

**Comment by nvandessel** [comment]
@webbertakken @GabLeRoux @davidmfinol 

Hey guys, wasn't sure who to tag so... :) 
I'd like to start tackling this problem, I've already setup what I think is the basic support for **public** scoped registries, however I was hoping to include the work to support private scoped registries as well. There's a few ways that we could solve this and so I wanted to open it up to discussion.

I'd like to try and support as many UPM registries types as possible. The only one I've personally used is Verdaccio (which I believe OpenUPM is also using as their backend registry), however I'd like to not be limited. In addition the authentication method with UPM registries is largely dependent on how you have decided to set it up as a user/organization. 

Ultimately the most important thing is that Unity requires a `.upmconfig.toml` located at a specific location dependent on your OS, which if it finds will utilize a token supplied there for authenticating with **private** scoped registries. I'd like to suggest that as a solution to support these private registries, we require that a consumer of the action sets a GH secret which is their private registry auth token, then during the execution of the action we pass that to `run_tests.sh` shell script which can determine if the value has been provided and setup the toml for us if it has. 

Curious to get your thoughts on this!

Also, shoutout to @trudeaua21 for all the work you put into supporting package testing!

**Comment by nvandessel** [comment]
I've implemented the solution I discussed above, supplying the registry token via a GitHub Actions Secret and creating the `.upmconfig.toml` on the fly. Everything looks to be working for both public and private scoped registries!

Looking forward to getting some feedback!

**Comment by nvandessel** [comment]
Discovered an issue in how multiple scopes were being parsed and injected into the `manifest.json`, I've fixed the issue and here's an example run showing it working: [fix: multiple scopes](https://github.com/luminopia/unity-test-runner/actions/runs/8101804152)

**Comment by nvandessel** [comment]
@webbertakken or @GabLeRoux, would love to get some feedback on this! 🙏

**Comment by GabLeRoux** [comment]
Wow, that is some amazing work here. I've only did a first pass, read descriptions and comments and gave a quick look at the modified files and it looks good so far. Thanks for this great contribution! I've added a reminder to go in details through the provided code tonight.

I personally don't own a package for Unity at this time, nor one that would have external dependencies, but I do understand the feature request so I'll dig into this and add a review asap 👍 

Nice one 🙌

**Review by GabLeRoux — APPROVED** [review]

**Review by webbertakken — APPROVED** [review]

**Pull request merged**
